version: '3.8'

services:
    nextjs:
        build: .
        container_name: nextjs-app
        restart: always
        env_file:
            - .env.production
        ports:
            - '3000:3000'

    nginx:
        image: nginx:stable-alpine
        container_name: nginx-proxy
        ports:
            - '80:80'
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - nextjs
